version: 2

jobs:
  backend:
    docker:
      - image: node:latest
    working_directory: $CIRCLE_WORKING_DIRECTORY/backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-dependencies-{{ checksum "package.json" }}
            - backend-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: backend-dependencies-{{ checksum "package.json" }}
      - run:
          name: yarn
          command: |
            yarn install
            yarn lint
            yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - backend
